const { ROLES } = require('./roles');

const PERMISSIONS = {
  // User Management
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_READ_ALL: 'user:read:all',

  // Student Management
  STUDENT_CREATE: 'student:create',
  STUDENT_READ: 'student:read',
  STUDENT_UPDATE: 'student:update',
  STUDENT_DELETE: 'student:delete',
  STUDENT_READ_ALL: 'student:read:all',

  // Faculty Management
  FACULTY_CREATE: 'faculty:create',
  FACULTY_READ: 'faculty:read',
  FACULTY_UPDATE: 'faculty:update',
  FACULTY_DELETE: 'faculty:delete',
  FACULTY_READ_ALL: 'faculty:read:all',

  // Department Management
  DEPARTMENT_CREATE: 'department:create',
  DEPARTMENT_READ: 'department:read',
  DEPARTMENT_UPDATE: 'department:update',
  DEPARTMENT_DELETE: 'department:delete',

  // Subject Management
  SUBJECT_CREATE: 'subject:create',
  SUBJECT_READ: 'subject:read',
  SUBJECT_UPDATE: 'subject:update',
  SUBJECT_DELETE: 'subject:delete',

  // Attendance
  ATTENDANCE_MARK: 'attendance:mark',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_UPDATE: 'attendance:update',
  ATTENDANCE_READ_ALL: 'attendance:read:all',

  // Marks & Exams
  MARKS_CREATE: 'marks:create',
  MARKS_READ: 'marks:read',
  MARKS_UPDATE: 'marks:update',
  MARKS_DELETE: 'marks:delete',
  EXAM_CREATE: 'exam:create',
  EXAM_READ: 'exam:read',
  EXAM_UPDATE: 'exam:update',

  // Fees
  FEE_CREATE: 'fee:create',
  FEE_READ: 'fee:read',
  FEE_UPDATE: 'fee:update',
  FEE_PAYMENT: 'fee:payment',
  FEE_READ_ALL: 'fee:read:all',

  // Timetable
  TIMETABLE_CREATE: 'timetable:create',
  TIMETABLE_READ: 'timetable:read',
  TIMETABLE_UPDATE: 'timetable:update',

  // Notices
  NOTICE_CREATE: 'notice:create',
  NOTICE_READ: 'notice:read',
  NOTICE_UPDATE: 'notice:update',
  NOTICE_DELETE: 'notice:delete',

  // LMS
  LMS_CONTENT_CREATE: 'lms:content:create',
  LMS_CONTENT_READ: 'lms:content:read',
  LMS_CONTENT_UPDATE: 'lms:content:update',
  LMS_ASSIGNMENT_CREATE: 'lms:assignment:create',
  LMS_ASSIGNMENT_SUBMIT: 'lms:assignment:submit',
  LMS_ASSIGNMENT_GRADE: 'lms:assignment:grade',

  // Placement
  PLACEMENT: {
    // Company Management
    CREATE_COMPANY: 'placement:company:create',
    VIEW_COMPANIES: 'placement:company:view',
    UPDATE_COMPANY: 'placement:company:update',
    DELETE_COMPANY: 'placement:company:delete',
    VERIFY_COMPANY: 'placement:company:verify',
    BLACKLIST_COMPANY: 'placement:company:blacklist',
    
    // Job Management
    CREATE_JOB: 'placement:job:create',
    VIEW_JOBS: 'placement:job:view',
    UPDATE_JOB: 'placement:job:update',
    DELETE_JOB: 'placement:job:delete',
    
    // Application Management
    APPLY_JOB: 'placement:application:apply',
    VIEW_APPLICATIONS: 'placement:application:view',
    UPDATE_APPLICATION_STATUS: 'placement:application:update_status',
    SCHEDULE_INTERVIEW: 'placement:application:schedule_interview',
    MAKE_OFFER: 'placement:application:make_offer',
    RESPOND_TO_OFFER: 'placement:application:respond_offer',
    
    // Statistics
    VIEW_STATISTICS: 'placement:statistics:view',
  },

  // Reports
  REPORT_GENERATE: 'report:generate',
  REPORT_READ: 'report:read',
  REPORT_EXPORT: 'report:export',

  // Audit Logs
  AUDIT_READ: 'audit:read',

  // Settings
  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',
};

// Role-Permission Matrix
const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // All permissions

  [ROLES.ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_READ_ALL,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.STUDENT_READ_ALL,
    PERMISSIONS.FACULTY_CREATE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_UPDATE,
    PERMISSIONS.FACULTY_DELETE,
    PERMISSIONS.FACULTY_READ_ALL,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_DELETE,
    PERMISSIONS.SUBJECT_CREATE,
    PERMISSIONS.SUBJECT_READ,
    PERMISSIONS.SUBJECT_UPDATE,
    PERMISSIONS.SUBJECT_DELETE,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_READ,
    PERMISSIONS.EXAM_UPDATE,
    PERMISSIONS.FEE_READ_ALL,
    PERMISSIONS.TIMETABLE_CREATE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.TIMETABLE_UPDATE,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTICE_UPDATE,
    PERMISSIONS.NOTICE_DELETE,
    PERMISSIONS.PLACEMENT.CREATE_COMPANY,
    PERMISSIONS.PLACEMENT.VIEW_COMPANIES,
    PERMISSIONS.PLACEMENT.UPDATE_COMPANY,
    PERMISSIONS.PLACEMENT.DELETE_COMPANY,
    PERMISSIONS.PLACEMENT.VERIFY_COMPANY,
    PERMISSIONS.PLACEMENT.BLACKLIST_COMPANY,
    PERMISSIONS.PLACEMENT.CREATE_JOB,
    PERMISSIONS.PLACEMENT.VIEW_JOBS,
    PERMISSIONS.PLACEMENT.UPDATE_JOB,
    PERMISSIONS.PLACEMENT.DELETE_JOB,
    PERMISSIONS.PLACEMENT.VIEW_APPLICATIONS,
    PERMISSIONS.PLACEMENT.UPDATE_APPLICATION_STATUS,
    PERMISSIONS.PLACEMENT.SCHEDULE_INTERVIEW,
    PERMISSIONS.PLACEMENT.MAKE_OFFER,
    PERMISSIONS.PLACEMENT.VIEW_STATISTICS,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_UPDATE,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_READ_ALL,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.MARKS_CREATE,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.MARKS_UPDATE,
    PERMISSIONS.EXAM_READ,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.LMS_CONTENT_CREATE,
    PERMISSIONS.LMS_CONTENT_READ,
    PERMISSIONS.LMS_CONTENT_UPDATE,
    PERMISSIONS.LMS_ASSIGNMENT_CREATE,
    PERMISSIONS.LMS_ASSIGNMENT_GRADE,
    PERMISSIONS.PLACEMENT.VIEW_COMPANIES,
    PERMISSIONS.PLACEMENT.VIEW_JOBS,
    PERMISSIONS.PLACEMENT.VIEW_STATISTICS,
    PERMISSIONS.REPORT_READ,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.EXAM_READ,
    PERMISSIONS.FEE_READ,
    PERMISSIONS.FEE_PAYMENT,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.LMS_CONTENT_READ,
    PERMISSIONS.LMS_ASSIGNMENT_SUBMIT,
    PERMISSIONS.PLACEMENT.VIEW_JOBS,
    PERMISSIONS.PLACEMENT.APPLY_JOB,
    PERMISSIONS.PLACEMENT.VIEW_APPLICATIONS,
    PERMISSIONS.PLACEMENT.RESPOND_TO_OFFER,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.EXAM_READ,
    PERMISSIONS.FEE_READ,
    PERMISSIONS.FEE_PAYMENT,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.NOTICE_READ,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.FEE_CREATE,
    PERMISSIONS.FEE_READ,
    PERMISSIONS.FEE_UPDATE,
    PERMISSIONS.FEE_READ_ALL,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
  ],

  [ROLES.PLACEMENT_OFFICER]: [
    PERMISSIONS.STUDENT_READ_ALL,
    PERMISSIONS.PLACEMENT.CREATE_COMPANY,
    PERMISSIONS.PLACEMENT.VIEW_COMPANIES,
    PERMISSIONS.PLACEMENT.UPDATE_COMPANY,
    PERMISSIONS.PLACEMENT.DELETE_COMPANY,
    PERMISSIONS.PLACEMENT.VERIFY_COMPANY,
    PERMISSIONS.PLACEMENT.CREATE_JOB,
    PERMISSIONS.PLACEMENT.VIEW_JOBS,
    PERMISSIONS.PLACEMENT.UPDATE_JOB,
    PERMISSIONS.PLACEMENT.DELETE_JOB,
    PERMISSIONS.PLACEMENT.VIEW_APPLICATIONS,
    PERMISSIONS.PLACEMENT.UPDATE_APPLICATION_STATUS,
    PERMISSIONS.PLACEMENT.SCHEDULE_INTERVIEW,
    PERMISSIONS.PLACEMENT.MAKE_OFFER,
    PERMISSIONS.PLACEMENT.VIEW_STATISTICS,
    PERMISSIONS.REPORT_READ,
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
